scrape_configs:
  - job_name: notifier
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
    scrape_interval: 5s
    static_configs:
      - targets:
        - notify:5501