version: '3'
services:
  notify:
    image: lordrahl/notify-server:latest
    container_name: "notify-backend"
    ports:
     - 5500:5500
     - 5501:5501

    depends_on: 
      - database
    networks:
      - notify

  database:
    image: mysql:5.7
    container_name: "notify_db"
    env_file: '../.envs/.mysql.env'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - notify


  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 5502:9090
    volumes:
      - ../.prometheus:/etc/prometheus
    networks:
      - notify
      
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 5503:3000
    networks:
      - notify

volumes:
  db_data:
    driver: local

networks:
  notify:
    driver: bridge